name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Type-check app
        run: npm run check -w app

      - name: Build app
        run: npm run build -w app

  validate-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
        with:
          go-version-file: cli/go.mod

      - name: Run vet
        run: go vet ./...
        working-directory: cli

      - name: Run tests
        run: go test ./...
        working-directory: cli
